import type { DashboardStats, InvoiceData } from "@/types/dashboard";
import { OfferData, ServiceData } from "@/types/market";
import { InvoiceDetailData, ServiceDetailData } from "@/types/modal";
import type { NFTData } from "@/types/nft";
import { OfferDatas } from "@/types/coral";
import { ServiceSubscriptionData } from "@/types/subscription";
// -------------------------------------------------DASHBOARD-------------------------------------------------
export const mockDashboardStats: DashboardStats = {
  totalInvoices: 100000000000,
  paidInvoices: 100000000000,
  unpaidInvoices: 100000000000,
};

export const mockInvoiceData: InvoiceData[] = [
  {
    id: "1",
    addressOwner: "0x123239424ihoedwjfn121123123",
    addressDebtor: "0x123jendjknefjnfnj924121123123",
    unitDebt: 1000,
    startDate: "2024-01-15T10:30:00Z",
    endDate: "2024-01-20T14:45:00Z",
    fieldCompany: "Water",
    status: "paid",
  },
  {
    id: "2",
    addressOwner: "0x456789abcdefghijklmnopqrstuvwxyz",
    addressDebtor: "0x987654321fedcba0987654321fedcba",
    unitDebt: 2500,
    startDate: "2024-01-10T08:15:00Z",
    endDate: "2024-01-18T16:30:00Z",
    fieldCompany: "Energy",
    status: "paid",
  },
  {
    id: "3",
    addressOwner: "0xabcdef123456789abcdef123456789",
    addressDebtor: "0x111222333444555666777888999000",
    unitDebt: 750,
    startDate: "2024-01-12T12:00:00Z",
    endDate: "2024-01-25T09:20:00Z",
    fieldCompany: "Gas",
    status: "unpaid",
  },
  {
    id: "4",
    addressOwner: "0x999888777666555444333222111000",
    addressDebtor: "0xfedcba0987654321fedcba0987654321",
    unitDebt: 1800,
    startDate: "2024-01-08T14:45:00Z",
    endDate: "2024-01-22T11:15:00Z",
    fieldCompany: "Water",
    status: "paid",
  },
  {
    id: "5",
    addressOwner: "0x147258369147258369147258369147",
    addressDebtor: "0x369258147369258147369258147369",
    unitDebt: 3200,
    startDate: "2024-01-20T16:30:00Z",
    endDate: "2024-02-05T10:45:00Z",
    fieldCompany: "Electricity",
    status: "unpaid",
  },
];

// ------------------------------------------------- Corals Market data-------------------------------------------------

export const mockNFTData: NFTData[] = [
  {
    id: "1",
    title: "Who the hell are you ?",
    // image:
    //   "https://i.pinimg.com/736x/16/e3/07/16e307ecb7336f3480028f4fb1f65be5.jpg",
    // image: "/data/nft-base-images/tier-1/retail.png",
    image: "/test-overlay.png",
    owner: "Lolololola",
    ownerAvatar: "/placeholder.svg?height=24&width=24",
    tokenCount: 9.4111111,
    startDate: "2024-01-15T10:30:00Z",
    endDate: "2025-07-20T14:45:30Z",
    rarity: "common",
    category: "Character",
  },
  {
    id: "2",
    title: "Who the hell are you ?",
    image:
      "https://i2.seadn.io/ethereum/0x8d04a8c79ceb0889bdd12acdf3fa9d207ed3ff63/c0fcdf6eff36c1d317a7248b0c7b0326.png?w=350",
    owner: "Lolololola",
    ownerAvatar: "/placeholder.svg?height=24&width=24",
    tokenCount: 9.41,
    startDate: "2024-01-10T08:15:00Z",
    endDate: "2024-01-18T16:30:45Z",
    rarity: "common",
    category: "Character",
  },
  {
    id: "3",
    title: "Who the hell are you ?",
    image:
      "https://i2.seadn.io/ethereum/0x8d04a8c79ceb0889bdd12acdf3fa9d207ed3ff63/2852bacb9aea64afbc2b0c5657e04d7f.png?w=350",
    owner: "Lolololola",
    ownerAvatar: "/placeholder.svg?height=24&width=24",
    tokenCount: 9.41,
    startDate: "2024-01-12T12:00:00Z",
    endDate: "2024-01-25T09:20:15Z",
    rarity: "rare",
    category: "Character",
  },
  {
    id: "4",
    title: "Who the hell are you ?",
    image:
      "https://i2.seadn.io/ethereum/0x8d04a8c79ceb0889bdd12acdf3fa9d207ed3ff63/12fedd765f414aad994f6397f26e6367.png?w=350",
    owner: "Lolololola",
    ownerAvatar: "/placeholder.svg?height=24&width=24",
    tokenCount: 9.41,
    startDate: "2024-01-08T14:45:00Z",
    endDate: "2024-01-22T11:15:30Z",
    rarity: "common",
    category: "Character",
  },
  {
    id: "5",
    title: "Who the hell are you ?",
    image:
      "https://i2.seadn.io/ethereum/0x8d04a8c79ceb0889bdd12acdf3fa9d207ed3ff63/35838a02b66bf9149b1ec7ea6d5256e3.png?w=350",
    owner: "Lolololola",
    ownerAvatar: "/placeholder.svg?height=24&width=24",
    tokenCount: 9.41,
    startDate: "2024-01-20T16:30:00Z",
    endDate: "2024-02-05T10:45:45Z",
    rarity: "epic",
    category: "Character",
  },
  {
    id: "6",
    title: "Who the hell are you ?",
    image:
      "https://i2.seadn.io/ethereum/0x232a68a51d6e07357ae025d2a459c16077327102/d8ec1c65324b53f9cbeca81514d63b/02d8ec1c65324b53f9cbeca81514d63b.gif?w=350",
    owner: "Lolololola",
    ownerAvatar: "/placeholder.svg?height=24&width=24",
    tokenCount: 9.41,
    startDate: "2024-01-05T09:00:00Z",
    endDate: "2024-01-12T18:30:20Z",
    rarity: "common",
    category: "Character",
  },
  {
    id: "7",
    title: "Who the hell are you ?",
    image:
      "https://i2.seadn.io/ethereum/0x232a68a51d6e07357ae025d2a459c16077327102/7bc62f4f37f17a6c3381afa4e4231e/b77bc62f4f37f17a6c3381afa4e4231e.gif?frame-time=1&w=350",
    owner: "Lolololola",
    ownerAvatar: "/placeholder.svg?height=24&width=24",
    tokenCount: 9.41,
    startDate: "2024-01-18T11:20:00Z",
    endDate: "2024-01-30T15:45:10Z",
    rarity: "common",
    category: "Character",
  },
  {
    id: "8",
    title: "Mystic Warrior",
    image:
      "https://i2.seadn.io/ethereum/0x232a68a51d6e07357ae025d2a459c16077327102/43ed2e556b1a463431707d9701e279/5843ed2e556b1a463431707d9701e279.gif?frame-time=1&w=350",
    owner: "Lolololola",
    ownerAvatar: "/placeholder.svg?height=24&width=24",
    tokenCount: 9.41,
    startDate: "2024-01-01T00:00:00Z",
    endDate: "2024-02-15T23:59:59Z",
    rarity: "legendary",
    category: "Anime",
  },
  {
    id: "9",
    title: "Who the hell are you ?",
    image:
      "https://i2.seadn.io/ethereum/0x8d04a8c79ceb0889bdd12acdf3fa9d207ed3ff63/c0fcdf6eff36c1d317a7248b0c7b0326.png?w=350",
    owner: "Lolololola",
    ownerAvatar: "/placeholder.svg?height=24&width=24",
    tokenCount: 9.41,
    startDate: "2024-01-14T07:30:00Z",
    endDate: "2024-01-28T19:45:25Z",
    rarity: "rare",
    category: "Character",
  },
  {
    id: "10",
    title: "Who the hell are you ?",
    image:
      "https://i2.seadn.io/ethereum/0x232a68a51d6e07357ae025d2a459c16077327102/43ed2e556b1a463431707d9701e279/5843ed2e556b1a463431707d9701e279.gif?frame-time=1&w=350",
    owner: "Lolololola",
    ownerAvatar: "/placeholder.svg?height=24&width=24",
    tokenCount: 9.41,
    startDate: "2024-01-22T13:15:00Z",
    endDate: "2024-02-01T08:30:40Z",
    rarity: "common",
    category: "Character",
  },
  {
    id: "11",
    title: "Who the hell are you ?",
    image:
      "https://i.pinimg.com/736x/16/e3/07/16e307ecb7336f3480028f4fb1f65be5.jpg",
    owner: "Lolololola",
    ownerAvatar: "/placeholder.svg?height=24&width=24",
    tokenCount: 9.41,
    startDate: "2024-01-03T15:45:00Z",
    endDate: "2024-01-16T12:20:35Z",
    rarity: "common",
    category: "Character",
  },
  {
    id: "12",
    title: "Who the hell are you ?",
    image:
      "https://i2.seadn.io/ethereum/0x8d04a8c79ceb0889bdd12acdf3fa9d207ed3ff63/2852bacb9aea64afbc2b0c5657e04d7f.png?w=350",
    owner: "Lolololola",
    ownerAvatar: "/placeholder.svg?height=24&width=24",
    tokenCount: 9.41,
    startDate: "2024-01-25T10:00:00Z",
    endDate: "2024-02-08T16:45:50Z",
    rarity: "common",
    category: "Character",
  },
  {
    id: "13",
    title: "Who the hell are you ?",
    image:
      "https://i2.seadn.io/ethereum/0x232a68a51d6e07357ae025d2a459c16077327102/d8ec1c65324b53f9cbeca81514d63b/02d8ec1c65324b53f9cbeca81514d63b.gif?w=350",
    owner: "Lolololola",
    ownerAvatar: "/placeholder.svg?height=24&width=24",
    tokenCount: 9.41,
    startDate: "2024-01-07T12:30:00Z",
    endDate: "2024-01-19T21:15:15Z",
    rarity: "rare",
    category: "Character",
  },
  {
    id: "14",
    title: "Who the hell are you ?",
    image:
      "https://i2.seadn.io/ethereum/0x8d04a8c79ceb0889bdd12acdf3fa9d207ed3ff63/12fedd765f414aad994f6397f26e6367.png?w=350",
    owner: "Lolololola",
    ownerAvatar: "/placeholder.svg?height=24&width=24",
    tokenCount: 9.41,
    startDate: "2024-01-11T08:45:00Z",
    endDate: "2024-01-24T17:30:25Z",
    rarity: "common",
    category: "Character",
  },
  {
    id: "15",
    title: "Who the hell are you ?",
    image:
      "https://i2.seadn.io/ethereum/0x232a68a51d6e07357ae025d2a459c16077327102/7bc62f4f37f17a6c3381afa4e4231e/b77bc62f4f37f17a6c3381afa4e4231e.gif?frame-time=1&w=350",
    owner: "Lolololola",
    ownerAvatar: "/placeholder.svg?height=24&width=24",
    tokenCount: 9.41,
    startDate: "2024-01-28T14:20:00Z",
    endDate: "2024-02-12T11:55:40Z",
    rarity: "epic",
    category: "Character",
  },
  // Additional NFTs for "Show More" functionality
  {
    id: "16",
    title: "Shadow Hunter",
    image:
      "https://i2.seadn.io/ethereum/0x8d04a8c79ceb0889bdd12acdf3fa9d207ed3ff63/35838a02b66bf9149b1ec7ea6d5256e3.png?w=350",
    owner: "CryptoKing",
    ownerAvatar: "/placeholder.svg?height=24&width=24",
    tokenCount: 12.5,
    startDate: "2024-01-02T06:00:00Z",
    endDate: "2024-01-20T18:30:45Z",
    rarity: "rare",
    category: "Character",
  },
  {
    id: "17",
    title: "Digital Phoenix",
    image:
      "https://i2.seadn.io/ethereum/0x8d04a8c79ceb0889bdd12acdf3fa9d207ed3ff63/c0fcdf6eff36c1d317a7248b0c7b0326.png?w=350",
    owner: "NFTCollector",
    ownerAvatar: "/placeholder.svg?height=24&width=24",
    tokenCount: 15.8,
    startDate: "2024-01-15T09:30:00Z",
    endDate: "2024-02-10T22:15:30Z",
    rarity: "epic",
    category: "Mythical",
  },
  {
    id: "18",
    title: "Cyber Samurai",
    image:
      "https://i.pinimg.com/736x/16/e3/07/16e307ecb7336f3480028f4fb1f65be5.jpg",
    owner: "TokenMaster",
    ownerAvatar: "/placeholder.svg?height=24&width=24",
    tokenCount: 20.3,
    startDate: "2024-01-01T12:00:00Z",
    endDate: "2024-03-01T12:00:00Z",
    rarity: "legendary",
    category: "Warrior",
  },
  {
    id: "19",
    title: "Neon Dreams",
    image:
      "https://i2.seadn.io/ethereum/0x8d04a8c79ceb0889bdd12acdf3fa9d207ed3ff63/2852bacb9aea64afbc2b0c5657e04d7f.png?w=350",
    owner: "ArtLover",
    ownerAvatar: "/placeholder.svg?height=24&width=24",
    tokenCount: 8.7,
    startDate: "2024-01-10T15:45:00Z",
    endDate: "2024-01-25T09:20:35Z",
    rarity: "common",
    category: "Abstract",
  },
  {
    id: "20",
    title: "Quantum Cat",
    image:
      "https://i2.seadn.io/ethereum/0x8d04a8c79ceb0889bdd12acdf3fa9d207ed3ff63/12fedd765f414aad994f6397f26e6367.png?w=350",
    owner: "QuantumUser",
    ownerAvatar: "/placeholder.svg?height=24&width=24",
    tokenCount: 11.2,
    startDate: "2024-01-05T11:15:00Z",
    endDate: "2024-01-28T16:45:20Z",
    rarity: "rare",
    category: "Character",
  },
];

export const mockServiceData: ServiceData[] = [
  {
    id: "1",
    businessName: "LavaLoon",
    businessLogo: "/placeholder.svg?height=40&width=40",
    serviceName: "Premium Analytics",
    price: 20,
    description: "Advanced analytics and reporting tools",
    category: "Analytics",
  },
  {
    id: "2",
    businessName: "LavaLoon",
    businessLogo: "/placeholder.svg?height=40&width=40",
    serviceName: "Cloud Storage Pro",
    price: 20,
    description: "Unlimited cloud storage with premium features",
    category: "Storage",
  },
  {
    id: "3",
    businessName: "LavaLoon",
    businessLogo: "/placeholder.svg?height=40&width=40",
    serviceName: "Security Suite",
    price: 20,
    description: "Complete security solution for your business",
    category: "Security",
  },
  {
    id: "4",
    businessName: "LavaLoon",
    businessLogo: "/placeholder.svg?height=40&width=40",
    serviceName: "Marketing Tools",
    price: 20,
    description: "Professional marketing automation platform",
    category: "Marketing",
  },
  {
    id: "5",
    businessName: "LavaLoon",
    businessLogo: "/placeholder.svg?height=40&width=40",
    serviceName: "API Gateway",
    price: 20,
    description: "Scalable API management and gateway service",
    category: "Development",
  },
  {
    id: "6",
    businessName: "LavaLoon",
    businessLogo: "/placeholder.svg?height=40&width=40",
    serviceName: "Database Pro",
    price: 20,
    description: "High-performance database solutions",
    category: "Database",
  },
  {
    id: "7",
    businessName: "LavaLoon",
    businessLogo: "/placeholder.svg?height=40&width=40",
    serviceName: "Monitoring Plus",
    price: 20,
    description: "Real-time monitoring and alerting system",
    category: "Monitoring",
  },
  {
    id: "8",
    businessName: "LavaLoon",
    businessLogo: "/placeholder.svg?height=40&width=40",
    serviceName: "Backup Solutions",
    price: 20,
    description: "Automated backup and disaster recovery",
    category: "Backup",
  },
  {
    id: "9",
    businessName: "LavaLoon",
    businessLogo: "/placeholder.svg?height=40&width=40",
    serviceName: "AI Assistant",
    price: 20,
    description: "Intelligent AI-powered business assistant",
    category: "AI",
  },
  {
    id: "10",
    businessName: "LavaLoon",
    businessLogo: "/placeholder.svg?height=40&width=40",
    serviceName: "Communication Hub",
    price: 20,
    description: "Unified communication platform",
    category: "Communication",
  },
  // Additional services for show more
  {
    id: "11",
    businessName: "TechFlow",
    businessLogo: "/placeholder.svg?height=40&width=40",
    serviceName: "Workflow Automation",
    price: 35,
    description: "Streamline your business processes",
    category: "Automation",
  },
  {
    id: "12",
    businessName: "DataVault",
    businessLogo: "/placeholder.svg?height=40&width=40",
    serviceName: "Enterprise Analytics",
    price: 50,
    description: "Enterprise-grade data analytics platform",
    category: "Analytics",
  },
];

export const mockBusinessesWithServices = [
  {
    id: "1",
    name: "LavaLoon",
    logo: "/placeholder.svg?height=40&width=40",
    address: "123 Main St, New York, NY",
    description: "Leading analytics and cloud solutions provider.",
    services: [
      {
        id: "1",
        businessName: "LavaLoon",
        businessLogo: "/placeholder.svg?height=40&width=40",
        serviceName: "Premium Analytics",
        price: 20,
        description: "Advanced analytics and reporting tools",
        category: "Analytics",
      },
      {
        id: "2",
        businessName: "LavaLoon",
        businessLogo: "/placeholder.svg?height=40&width=40",
        serviceName: "Cloud Storage Pro",
        price: 20,
        description: "Unlimited cloud storage with premium features",
        category: "Storage",
      },
      // ...more services
    ],
  },
  {
    id: "2",
    name: "TechFlow",
    logo: "/placeholder.svg?height=40&width=40",
    address: "456 Tech Ave, San Francisco, CA",
    description: "Workflow automation and enterprise software.",
    services: [
      {
        id: "11",
        businessName: "TechFlow",
        businessLogo: "/placeholder.svg?height=40&width=40",
        serviceName: "Workflow Automation",
        price: 35,
        description: "Streamline your business processes",
        category: "Automation",
      },
      // ...more services
    ],
  },
  // ...add more businesses, each with their own services
];
// ---------------------------------------------------------------------------------------------------------------
export const getInvoiceDetail = (offerId: string): InvoiceDetailData => {
  return {
    id: offerId,
    debtorAddress: "0x742d35Cc6634C0532925a3b8D4C9db96590b5b8e",
    description:
      "This NFT represents a unique digital collectible featuring an exclusive character design. The artwork includes special traits and rarity attributes that make it valuable for collectors and traders in the NFT marketplace.",
    startDate: "2024-01-15",
    endDate: "2024-01-30",
    products: [
      {
        id: "1",
        name: "NFT Character License",
        price: 150,
        quantity: 1,
      },
      {
        id: "2",
        name: "Commercial Usage Rights",
        price: 50,
        quantity: 1,
      },
      {
        id: "3",
        name: "High Resolution Assets",
        price: 25,
        quantity: 2,
      },
    ],
    total: {
      price: 250,
      quantity: 4,
    },
  };
};

export const getServiceDetail = (serviceId: string): ServiceDetailData => {
  return {
    id: serviceId,
    serviceName: "Premium Analytics Suite",
    businessName: "LavaLoon",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    startDate: "01/11/2025",
    endDate: "01/11/2026",
    price: 20,
    features: [
      "Real-time data analytics",
      "Custom dashboard creation",
      "Advanced reporting tools",
      "API integration support",
      "24/7 customer support",
    ],
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-lYmmjSZAbS3GTaHKdhjr2G5OhMBRrf.png",
  };
};

// -------------------------------------Service---------------------------------------

export const getServiceSubscriptionData = (
  serviceId: string
): ServiceSubscriptionData => {
  // Different form configurations for different services
  const formConfigs: Record<string, ServiceSubscriptionData> = {
    "1": {
      serviceId: "1",
      serviceName: "Premium Analytics",
      businessName: "LavaLoon",
      price: 20,
      formConfig: {
        email: true,
        fullName: true,
        phone: true,
        address: false,
        zipcode: false,
        nationality: false,
        personalId: false,
        sex: false,
        birthdate: false,
        image: false,
        taxId: false,
        kycImage: false,
      },
    },
    "2": {
      serviceId: "2",
      serviceName: "Cloud Storage Pro",
      businessName: "LavaLoon",
      price: 20,
      formConfig: {
        email: true,
        fullName: true,
        phone: true,
        address: true,
        zipcode: true,
        nationality: false,
        personalId: false,
        sex: false,
        birthdate: false,
        image: false,
        taxId: false,
        kycImage: false,
      },
    },
    "3": {
      serviceId: "3",
      serviceName: "Security Suite",
      businessName: "LavaLoon",
      price: 20,
      formConfig: {
        email: true,
        fullName: true,
        phone: true,
        address: true,
        zipcode: true,
        nationality: true,
        personalId: true,
        sex: true,
        birthdate: true,
        image: true,
        taxId: false,
        kycImage: true,
      },
    },
    "4": {
      serviceId: "4",
      serviceName: "Marketing Tools",
      businessName: "LavaLoon",
      price: 20,
      formConfig: {
        email: true,
        fullName: true,
        phone: true,
        address: true,
        zipcode: false,
        nationality: false,
        personalId: false,
        sex: false,
        birthdate: false,
        image: false,
        taxId: true,
        kycImage: false,
      },
    },
    "5": {
      serviceId: "5",
      serviceName: "API Gateway",
      businessName: "LavaLoon",
      price: 20,
      formConfig: {
        email: true,
        fullName: true,
        phone: false,
        address: false,
        zipcode: false,
        nationality: false,
        personalId: false,
        sex: false,
        birthdate: false,
        image: false,
        taxId: false,
        kycImage: false,
      },
    },
  };

  return (
    formConfigs[serviceId] || {
      serviceId,
      serviceName: "Unknown Service",
      businessName: "Unknown Business",
      price: 0,
      formConfig: {
        email: true,
        fullName: true,
        phone: false,
        address: false,
        zipcode: false,
        nationality: false,
        personalId: false,
        sex: false,
        birthdate: false,
        image: false,
        taxId: false,
        kycImage: false,
      },
    }
  );
};

// --------------------------
export const mockOfferDatas: OfferDatas[] = [
  {
    id: "1",
    invoiceAddress: "0x742d35Cc6634C0532925a3b8D4C9db96590b5b8e",
    pricing: 1500.0,
    contactInfo: {
      name: "John Smith",
      email: "john.smith@company.com",
      phone: "+1 (555) 123-4567",
      company: "Tech Solutions Inc",
      address: "123 Business St, New York, NY 10001",
    },
    startDate: "2024-01-15",
    endDate: "2024-03-15",
    agreements: ["service_agreement.pdf", "terms_conditions.pdf"],
    status: "active",
    createdAt: "2024-01-10T10:30:00Z",
    updatedAt: "2024-01-10T10:30:00Z",
  },
  {
    id: "2",
    invoiceAddress: "0x123456789abcdef123456789abcdef123456789a",
    pricing: 2800.5,
    contactInfo: {
      name: "Sarah Johnson",
      email: "sarah.j@digitalcorp.com",
      phone: "+1 (555) 987-6543",
      company: "Digital Corp",
      address: "456 Innovation Ave, San Francisco, CA 94105",
    },
    startDate: "2024-02-01",
    endDate: "2024-04-30",
    agreements: ["contract.pdf", "nda.pdf", "payment_terms.pdf"],
    status: "pending",
    createdAt: "2024-01-25T14:20:00Z",
    updatedAt: "2024-01-25T14:20:00Z",
  },
  {
    id: "3",
    invoiceAddress: "0xabcdef123456789abcdef123456789abcdef1234",
    pricing: 950.0,
    contactInfo: {
      name: "Michael Chen",
      email: "m.chen@startupventures.io",
      phone: "+1 (555) 456-7890",
      company: "Startup Ventures",
      address: "789 Entrepreneur Blvd, Austin, TX 73301",
    },
    startDate: "2024-01-20",
    endDate: "2024-02-20",
    agreements: ["service_contract.pdf"],
    status: "expired",
    createdAt: "2024-01-15T09:15:00Z",
    updatedAt: "2024-01-15T09:15:00Z",
  },
  {
    id: "4",
    invoiceAddress: "0x987654321fedcba987654321fedcba987654321f",
    pricing: 3200.75,
    contactInfo: {
      name: "Emily Rodriguez",
      email: "emily.r@globaltech.com",
      phone: "+1 (555) 321-0987",
      company: "Global Tech Solutions",
      address: "321 Corporate Dr, Chicago, IL 60601",
    },
    startDate: "2024-03-01",
    endDate: "2024-06-01",
    agreements: ["master_agreement.pdf", "sow.pdf"],
    status: "draft",
    createdAt: "2024-02-28T16:45:00Z",
    updatedAt: "2024-02-28T16:45:00Z",
  },
  {
    id: "5",
    invoiceAddress: "0x456789abcdef123456789abcdef123456789abcd",
    pricing: 1750.25,
    contactInfo: {
      name: "David Wilson",
      email: "d.wilson@innovateplus.com",
      phone: "+1 (555) 654-3210",
      company: "Innovate Plus",
      address: "654 Future St, Seattle, WA 98101",
    },
    startDate: "2024-02-15",
    endDate: "2024-05-15",
    agreements: [
      "partnership_agreement.pdf",
      "terms.pdf",
      "privacy_policy.pdf",
    ],
    status: "active",
    createdAt: "2024-02-10T11:30:00Z",
    updatedAt: "2024-02-10T11:30:00Z",
  },
  {
    id: "6",
    invoiceAddress: "0xfedcba987654321fedcba987654321fedcba9876",
    pricing: 4500.0,
    contactInfo: {
      name: "Lisa Thompson",
      email: "lisa.t@enterprisesolutions.com",
      phone: "+1 (555) 789-0123",
      company: "Enterprise Solutions",
      address: "987 Business Park, Boston, MA 02101",
    },
    startDate: "2024-01-01",
    endDate: "2024-12-31",
    agreements: [
      "annual_contract.pdf",
      "sla.pdf",
      "data_processing.pdf",
      "compliance.pdf",
    ],
    status: "active",
    createdAt: "2023-12-20T08:00:00Z",
    updatedAt: "2023-12-20T08:00:00Z",
  },
  {
    id: "7",
    invoiceAddress: "0x111222333444555666777888999000aaabbbccc",
    pricing: 825.5,
    contactInfo: {
      name: "Robert Kim",
      email: "r.kim@techstartup.io",
      phone: "+1 (555) 147-2580",
      company: "Tech Startup",
      address: "147 Innovation Hub, Portland, OR 97201",
    },
    startDate: "2024-02-20",
    endDate: "2024-03-20",
    agreements: ["pilot_agreement.pdf"],
    status: "pending",
    createdAt: "2024-02-15T13:20:00Z",
    updatedAt: "2024-02-15T13:20:00Z",
  },
  {
    id: "8",
    invoiceAddress: "0xaaabbbccc111222333444555666777888999000",
    pricing: 6750.0,
    contactInfo: {
      name: "Amanda Foster",
      email: "a.foster@megacorp.com",
      phone: "+1 (555) 369-2580",
      company: "MegaCorp Industries",
      address: "369 Corporate Plaza, Miami, FL 33101",
    },
    startDate: "2024-03-15",
    endDate: "2024-09-15",
    agreements: ["enterprise_contract.pdf", "security_addendum.pdf"],
    status: "draft",
    createdAt: "2024-03-10T15:45:00Z",
    updatedAt: "2024-03-10T15:45:00Z",
  },
  {
    id: "9",
    invoiceAddress: "0xabc123def456789abc123def456789abc123def4",
    pricing: 2100.0,
    contactInfo: {
      name: "Olivia Martinez",
      email: "olivia.martinez@fintechhub.com",
      phone: "+1 (555) 321-6549",
      company: "Fintech Hub",
      address: "321 Fintech Ave, Dallas, TX 75201",
    },
    startDate: "2024-04-01",
    endDate: "2024-07-01",
    agreements: ["fintech_agreement.pdf", "nda.pdf"],
    status: "active",
    createdAt: "2024-03-25T09:00:00Z",
    updatedAt: "2024-03-25T09:00:00Z",
  },
  {
    id: "10",
    invoiceAddress: "0xdef789abc123456def789abc123456def789abc1",
    pricing: 3900.75,
    contactInfo: {
      name: "Carlos Rivera",
      email: "c.rivera@cloudinnovate.com",
      phone: "+1 (555) 852-9637",
      company: "Cloud Innovate",
      address: "852 Cloud St, Denver, CO 80202",
    },
    startDate: "2024-05-10",
    endDate: "2024-08-10",
    agreements: ["cloud_service_agreement.pdf"],
    status: "pending",
    createdAt: "2024-05-01T11:15:00Z",
    updatedAt: "2024-05-01T11:15:00Z",
  },
  {
    id: "11",
    invoiceAddress: "0x789abc456def123789abc456def123789abc456d",
    pricing: 1200.5,
    contactInfo: {
      name: "Priya Singh",
      email: "priya.singh@meditech.com",
      phone: "+1 (555) 963-7412",
      company: "MediTech Solutions",
      address: "963 Health Blvd, Los Angeles, CA 90001",
    },
    startDate: "2024-06-05",
    endDate: "2024-09-05",
    agreements: ["meditech_contract.pdf", "privacy_policy.pdf"],
    status: "draft",
    createdAt: "2024-05-30T14:40:00Z",
    updatedAt: "2024-05-30T14:40:00Z",
  },
];
// -----------------------------------------------ALL SERVICES DATA-----------------------------------------------

export const mockBusinesses = [
  {
    id: "1",
    name: "TechCorp Solutions",
    logo: "/placeholder.svg",
    description: "Leading technology solutions provider",
    trending: [
      {
        id: "101",
        name: "Gaming Laptop Pro",
        price: 1299,
        image: "/placeholder.svg?height=200&width=280",
        business: "TechCorp Solutions",
        category: "Electronics",
        type: "goods" as const,
        sales: 456,
        rating: 4.8,
        reviews: 89,
        description:
          "High-performance gaming laptop with RTX graphics and 16GB RAM.",
        isFavorite: false,
      },
      {
        id: "102",
        name: "Wireless Earbuds Premium",
        price: 199,
        image: "/placeholder.svg?height=200&width=280",
        business: "TechCorp Solutions",
        category: "Electronics",
        type: "goods" as const,
        sales: 1234,
        rating: 4.6,
        reviews: 234,
        description: "Premium wireless earbuds with active noise cancellation.",
        isFavorite: true,
      },
      {
        id: "1",
        name: "Tech Support Premium",
        price: 49,
        image: "/placeholder.svg?height=200&width=280",
        business: "TechCorp Solutions",
        category: "Business",
        type: "service" as const,
        sales: 340,
        rating: 4.7,
        reviews: 23,
        description:
          "24/7 premium tech support with remote assistance and priority response.",
        isFavorite: false,
      },
    ],
    bestSellers: [
      {
        id: "103",
        name: "Smart Home Hub",
        price: 299,
        image: "/placeholder.svg?height=200&width=280",
        business: "TechCorp Solutions",
        category: "Electronics",
        type: "goods" as const,
        sales: 2345,
        rating: 4.9,
        reviews: 567,
        description:
          "Central smart home control hub with voice commands and app integration.",
        isFavorite: true,
      },
      {
        id: "104",
        name: "4K Webcam",
        price: 149,
        image: "/placeholder.svg?height=200&width=280",
        business: "TechCorp Solutions",
        category: "Electronics",
        type: "goods" as const,
        sales: 1567,
        rating: 4.7,
        reviews: 345,
        description:
          "Professional 4K webcam with auto-focus and low-light correction.",
        isFavorite: false,
      },
      {
        id: "2",
        name: "Cloud Storage Pro",
        price: 29,
        image: "/placeholder.svg?height=200&width=280",
        business: "TechCorp Solutions",
        category: "Business",
        type: "service" as const,
        sales: 567,
        rating: 4.5,
        reviews: 45,
        description:
          "Secure cloud storage with 1TB space, automatic backup, and file sharing.",
        isFavorite: false,
      },
      {
        id: "5",
        name: "App Development Service",
        price: 499,
        image: "/placeholder.svg?height=200&width=280",
        business: "TechCorp Solutions",
        category: "Business",
        type: "service" as const,
        sales: 89,
        rating: 4.8,
        reviews: 19,
        description:
          "Custom mobile app development for iOS and Android platforms.",
        isFavorite: true,
      },
    ],
    goods: [
      {
        id: "105",
        name: "Mechanical Keyboard RGB",
        price: 179,
        image: "/placeholder.svg?height=200&width=280",
        business: "TechCorp Solutions",
        category: "Electronics",
        type: "goods" as const,
        sales: 789,
        rating: 4.8,
        reviews: 156,
        description:
          "Mechanical gaming keyboard with RGB backlighting and custom switches.",
        isFavorite: false,
      },
      {
        id: "106",
        name: "Wireless Charging Pad",
        price: 59,
        image: "/placeholder.svg?height=200&width=280",
        business: "TechCorp Solutions",
        category: "Electronics",
        type: "goods" as const,
        sales: 567,
        rating: 4.5,
        reviews: 123,
        description:
          "Fast wireless charging pad compatible with all Qi-enabled devices.",
        isFavorite: false,
      },
      {
        id: "107",
        name: "USB-C Hub Multi-Port",
        price: 89,
        image: "/placeholder.svg?height=200&width=280",
        business: "TechCorp Solutions",
        category: "Electronics",
        type: "goods" as const,
        sales: 345,
        rating: 4.6,
        reviews: 78,
        description:
          "7-in-1 USB-C hub with HDMI, USB 3.0, SD card slots, and power delivery.",
        isFavorite: false,
      },
      {
        id: "108",
        name: "Bluetooth Speaker Portable",
        price: 129,
        image: "/placeholder.svg?height=200&width=280",
        business: "TechCorp Solutions",
        category: "Electronics",
        type: "goods" as const,
        sales: 678,
        rating: 4.7,
        reviews: 145,
        description:
          "Waterproof portable Bluetooth speaker with 20-hour battery life.",
        isFavorite: true,
      },
      {
        id: "109",
        name: "Smart Watch Fitness",
        price: 249,
        image: "/placeholder.svg?height=200&width=280",
        business: "TechCorp Solutions",
        category: "Electronics",
        type: "goods" as const,
        sales: 456,
        rating: 4.4,
        reviews: 98,
        description:
          "Fitness tracking smartwatch with heart rate monitor and GPS.",
        isFavorite: false,
      },
      {
        id: "110",
        name: "Phone Case Protective",
        price: 29,
        image: "/placeholder.svg?height=200&width=280",
        business: "TechCorp Solutions",
        category: "Electronics",
        type: "goods" as const,
        sales: 1234,
        rating: 4.3,
        reviews: 267,
        description:
          "Shockproof protective phone case with raised edges and screen protection.",
        isFavorite: false,
      },
    ],
    services: [
      {
        id: "1",
        name: "Tech Support Premium",
        price: 49,
        image: "/placeholder.svg?height=200&width=280",
        business: "TechCorp Solutions",
        category: "Business",
        type: "service" as const,
        sales: 340,
        rating: 4.7,
        reviews: 23,
        description:
          "24/7 premium tech support with remote assistance and priority response.",
        isFavorite: false,
      },
      {
        id: "2",
        name: "Cloud Storage Pro",
        price: 29,
        image: "/placeholder.svg?height=200&width=280",
        business: "TechCorp Solutions",
        category: "Business",
        type: "service" as const,
        sales: 567,
        rating: 4.5,
        reviews: 45,
        description:
          "Secure cloud storage with 1TB space, automatic backup, and file sharing.",
        isFavorite: false,
      },
      {
        id: "3",
        name: "Website Design Service",
        price: 299,
        image: "/placeholder.svg?height=200&width=280",
        business: "TechCorp Solutions",
        category: "Design",
        type: "service" as const,
        sales: 123,
        rating: 4.9,
        reviews: 34,
        description:
          "Professional website design service with responsive layout and SEO optimization.",
        isFavorite: false,
      },
      {
        id: "4",
        name: "Digital Marketing Package",
        price: 199,
        image: "/placeholder.svg?height=200&width=280",
        business: "TechCorp Solutions",
        category: "Business",
        type: "service" as const,
        sales: 234,
        rating: 4.6,
        reviews: 28,
        description:
          "Complete digital marketing package including SEO, social media, and content creation.",
        isFavorite: false,
      },
      {
        id: "5",
        name: "App Development Service",
        price: 499,
        image: "/placeholder.svg?height=200&width=280",
        business: "TechCorp Solutions",
        category: "Business",
        type: "service" as const,
        sales: 89,
        rating: 4.8,
        reviews: 19,
        description:
          "Custom mobile app development for iOS and Android platforms.",
        isFavorite: true,
      },
      {
        id: "6",
        name: "Database Management",
        price: 149,
        image: "/placeholder.svg?height=200&width=280",
        business: "TechCorp Solutions",
        category: "Business",
        type: "service" as const,
        sales: 156,
        rating: 4.4,
        reviews: 21,
        description:
          "Professional database design, optimization, and maintenance services.",
        isFavorite: false,
      },
    ],
  },
  {
    id: "2",
    name: "Creative Studios",
    logo: "/placeholder.svg",
    description: "Premium design and multimedia services",
    trending: [
      {
        id: "201",
        name: "Digital Art Tablet",
        price: 399,
        image: "/placeholder.svg?height=200&width=280",
        business: "Creative Studios",
        category: "Art & Design",
        type: "goods" as const,
        sales: 234,
        rating: 4.8,
        reviews: 67,
        description:
          "Professional digital art tablet with pressure-sensitive pen and 2K display.",
        isFavorite: false,
      },
      {
        id: "202",
        name: "Design Software License",
        price: 299,
        image: "/placeholder.svg?height=200&width=280",
        business: "Creative Studios",
        category: "Software",
        type: "goods" as const,
        sales: 567,
        rating: 4.9,
        reviews: 123,
        description:
          "Professional design software suite with lifetime updates and cloud storage.",
        isFavorite: true,
      },
      {
        id: "8",
        name: "Video Production",
        price: 799,
        image: "/placeholder.svg?height=200&width=280",
        business: "Creative Studios",
        category: "Media",
        type: "service" as const,
        sales: 234,
        rating: 4.9,
        reviews: 67,
        description:
          "Complete video production service from script to final edit.",
        isFavorite: true,
      },
    ],
    bestSellers: [
      {
        id: "203",
        name: "Professional Camera Kit",
        price: 1299,
        image: "/placeholder.svg?height=200&width=280",
        business: "Creative Studios",
        category: "Photography",
        type: "goods" as const,
        sales: 1456,
        rating: 4.9,
        reviews: 345,
        description:
          "Complete camera kit with DSLR, lenses, tripod, and accessories.",
        isFavorite: true,
      },
      {
        id: "204",
        name: "Studio Lighting Set",
        price: 599,
        image: "/placeholder.svg?height=200&width=280",
        business: "Creative Studios",
        category: "Photography",
        type: "goods" as const,
        sales: 987,
        rating: 4.7,
        reviews: 234,
        description:
          "Professional 3-light studio setup with softboxes and stands.",
        isFavorite: false,
      },
      {
        id: "7",
        name: "Logo Design Package",
        price: 199,
        image: "/placeholder.svg?height=200&width=280",
        business: "Creative Studios",
        category: "Design",
        type: "service" as const,
        sales: 890,
        rating: 4.8,
        reviews: 124,
        description:
          "Professional logo design with multiple concepts and unlimited revisions.",
        isFavorite: false,
      },
      {
        id: "9",
        name: "Brand Identity Package",
        price: 599,
        image: "/placeholder.svg?height=200&width=280",
        business: "Creative Studios",
        category: "Design",
        type: "service" as const,
        sales: 345,
        rating: 4.7,
        reviews: 89,
        description:
          "Complete brand identity including logo, colors, typography, and guidelines.",
        isFavorite: false,
      },
    ],
    goods: [
      {
        id: "205",
        name: "Graphic Design Book Collection",
        price: 89,
        image: "/placeholder.svg?height=200&width=280",
        business: "Creative Studios",
        category: "Books",
        type: "goods" as const,
        sales: 345,
        rating: 4.6,
        reviews: 78,
        description:
          "Collection of 5 essential graphic design books for creative inspiration.",
        isFavorite: false,
      },
      {
        id: "206",
        name: "Color Palette Guide",
        price: 39,
        image: "/placeholder.svg?height=200&width=280",
        business: "Creative Studios",
        category: "Art & Design",
        type: "goods" as const,
        sales: 567,
        rating: 4.5,
        reviews: 123,
        description:
          "Comprehensive color palette guide with 1000+ color combinations.",
        isFavorite: false,
      },
      {
        id: "207",
        name: "Typography Poster Set",
        price: 59,
        image: "/placeholder.svg?height=200&width=280",
        business: "Creative Studios",
        category: "Art & Design",
        type: "goods" as const,
        sales: 234,
        rating: 4.7,
        reviews: 56,
        description:
          "Set of 10 educational typography posters for design inspiration.",
        isFavorite: false,
      },
      {
        id: "208",
        name: "Sketch Pad Professional",
        price: 29,
        image: "/placeholder.svg?height=200&width=280",
        business: "Creative Studios",
        category: "Art & Design",
        type: "goods" as const,
        sales: 789,
        rating: 4.4,
        reviews: 167,
        description:
          "High-quality sketch pad with thick paper perfect for design concepts.",
        isFavorite: false,
      },
      {
        id: "209",
        name: "Digital Brushes Collection",
        price: 49,
        image: "/placeholder.svg?height=200&width=280",
        business: "Creative Studios",
        category: "Software",
        type: "goods" as const,
        sales: 678,
        rating: 4.8,
        reviews: 145,
        description:
          "Collection of 200+ professional digital brushes for design software.",
        isFavorite: true,
      },
      {
        id: "210",
        name: "Video Editing Course",
        price: 199,
        image: "/placeholder.svg?height=200&width=280",
        business: "Creative Studios",
        category: "Education",
        type: "goods" as const,
        sales: 456,
        rating: 4.9,
        reviews: 98,
        description:
          "Comprehensive video editing course with software and project files.",
        isFavorite: false,
      },
    ],
    services: [
      {
        id: "7",
        name: "Logo Design Package",
        price: 199,
        image: "/placeholder.svg?height=200&width=280",
        business: "Creative Studios",
        category: "Design",
        type: "service" as const,
        sales: 890,
        rating: 4.8,
        reviews: 124,
        description:
          "Professional logo design with multiple concepts and unlimited revisions.",
        isFavorite: false,
      },
      {
        id: "8",
        name: "Video Production",
        price: 799,
        image: "/placeholder.svg?height=200&width=280",
        business: "Creative Studios",
        category: "Media",
        type: "service" as const,
        sales: 234,
        rating: 4.9,
        reviews: 67,
        description:
          "Complete video production service from script to final edit.",
        isFavorite: true,
      },
      {
        id: "9",
        name: "Brand Identity Package",
        price: 599,
        image: "/placeholder.svg?height=200&width=280",
        business: "Creative Studios",
        category: "Design",
        type: "service" as const,
        sales: 345,
        rating: 4.7,
        reviews: 89,
        description:
          "Complete brand identity including logo, colors, typography, and guidelines.",
        isFavorite: false,
      },
      {
        id: "10",
        name: "Photography Session",
        price: 299,
        image: "/placeholder.svg?height=200&width=280",
        business: "Creative Studios",
        category: "Media",
        type: "service" as const,
        sales: 567,
        rating: 4.6,
        reviews: 98,
        description:
          "Professional photography session with edited high-resolution images.",
        isFavorite: false,
      },
      {
        id: "11",
        name: "Social Media Content",
        price: 149,
        image: "/placeholder.svg?height=200&width=280",
        business: "Creative Studios",
        category: "Marketing",
        type: "service" as const,
        sales: 678,
        rating: 4.5,
        reviews: 143,
        description:
          "Monthly social media content creation with graphics and captions.",
        isFavorite: false,
      },
    ],
  },
  {
    id: "3",
    name: "HealthPlus Wellness",
    logo: "/placeholder.svg",
    description: "Comprehensive health and wellness services",
    trending: [
      {
        id: "301",
        name: "Fitness Tracker Pro",
        price: 199,
        image: "/placeholder.svg?height=200&width=280",
        business: "HealthPlus Wellness",
        category: "Health & Fitness",
        type: "goods" as const,
        sales: 678,
        rating: 4.7,
        reviews: 145,
        description:
          "Advanced fitness tracker with heart rate, sleep, and stress monitoring.",
        isFavorite: false,
      },
      {
        id: "302",
        name: "Yoga Mat Premium",
        price: 79,
        image: "/placeholder.svg?height=200&width=280",
        business: "HealthPlus Wellness",
        category: "Health & Fitness",
        type: "goods" as const,
        sales: 1234,
        rating: 4.8,
        reviews: 267,
        description:
          "Non-slip premium yoga mat with alignment guides and carrying strap.",
        isFavorite: true,
      },
      {
        id: "14",
        name: "Yoga Classes",
        price: 79,
        image: "/placeholder.svg?height=200&width=280",
        business: "HealthPlus Wellness",
        category: "Health",
        type: "service" as const,
        sales: 789,
        rating: 4.6,
        reviews: 167,
        description: "Group and private yoga classes for all skill levels.",
        isFavorite: true,
      },
    ],
    bestSellers: [
      {
        id: "303",
        name: "Protein Powder Organic",
        price: 59,
        image: "/placeholder.svg?height=200&width=280",
        business: "HealthPlus Wellness",
        category: "Supplements",
        type: "goods" as const,
        sales: 1567,
        rating: 4.6,
        reviews: 334,
        description:
          "Organic plant-based protein powder with 25g protein per serving.",
        isFavorite: false,
      },
      {
        id: "304",
        name: "Resistance Bands Set",
        price: 39,
        image: "/placeholder.svg?height=200&width=280",
        business: "HealthPlus Wellness",
        category: "Health & Fitness",
        type: "goods" as const,
        sales: 987,
        rating: 4.5,
        reviews: 234,
        description:
          "Complete resistance bands set with different resistance levels and door anchor.",
        isFavorite: false,
      },
      {
        id: "12",
        name: "Personal Training",
        price: 89,
        image: "/placeholder.svg?height=200&width=280",
        business: "HealthPlus Wellness",
        category: "Health",
        type: "service" as const,
        sales: 456,
        rating: 4.8,
        reviews: 78,
        description:
          "One-on-one personal training sessions with certified trainers.",
        isFavorite: false,
      },
      {
        id: "15",
        name: "Massage Therapy",
        price: 129,
        image: "/placeholder.svg?height=200&width=280",
        business: "HealthPlus Wellness",
        category: "Health",
        type: "service" as const,
        sales: 345,
        rating: 4.9,
        reviews: 89,
        description:
          "Therapeutic massage sessions for relaxation and pain relief.",
        isFavorite: false,
      },
    ],
    goods: [
      {
        id: "305",
        name: "Adjustable Dumbbells",
        price: 299,
        image: "/placeholder.svg?height=200&width=280",
        business: "HealthPlus Wellness",
        category: "Health & Fitness",
        type: "goods" as const,
        sales: 345,
        rating: 4.8,
        reviews: 89,
        description:
          "Space-saving adjustable dumbbells with quick weight selection system.",
        isFavorite: false,
      },
      {
        id: "306",
        name: "Essential Oils Set",
        price: 89,
        image: "/placeholder.svg?height=200&width=280",
        business: "HealthPlus Wellness",
        category: "Wellness",
        type: "goods" as const,
        sales: 567,
        rating: 4.7,
        reviews: 123,
        description:
          "Set of 10 pure essential oils for aromatherapy and relaxation.",
        isFavorite: false,
      },
      {
        id: "307",
        name: "Meditation Cushion",
        price: 49,
        image: "/placeholder.svg?height=200&width=280",
        business: "HealthPlus Wellness",
        category: "Wellness",
        type: "goods" as const,
        sales: 234,
        rating: 4.6,
        reviews: 67,
        description:
          "Comfortable meditation cushion with organic buckwheat filling.",
        isFavorite: false,
      },
      {
        id: "308",
        name: "Water Bottle Smart",
        price: 69,
        image: "/placeholder.svg?height=200&width=280",
        business: "HealthPlus Wellness",
        category: "Health & Fitness",
        type: "goods" as const,
        sales: 456,
        rating: 4.5,
        reviews: 98,
        description:
          "Smart water bottle that tracks hydration and reminds you to drink.",
        isFavorite: true,
      },
      {
        id: "309",
        name: "Sleep Mask Weighted",
        price: 29,
        image: "/placeholder.svg?height=200&width=280",
        business: "HealthPlus Wellness",
        category: "Wellness",
        type: "goods" as const,
        sales: 789,
        rating: 4.4,
        reviews: 167,
        description:
          "Weighted sleep mask for better relaxation and deeper sleep.",
        isFavorite: false,
      },
      {
        id: "310",
        name: "Foam Roller Massage",
        price: 59,
        image: "/placeholder.svg?height=200&width=280",
        business: "HealthPlus Wellness",
        category: "Health & Fitness",
        type: "goods" as const,
        sales: 345,
        rating: 4.7,
        reviews: 78,
        description:
          "High-density foam roller for muscle recovery and pain relief.",
        isFavorite: false,
      },
    ],
    services: [
      {
        id: "12",
        name: "Personal Training",
        price: 89,
        image: "/placeholder.svg?height=200&width=280",
        business: "HealthPlus Wellness",
        category: "Health",
        type: "service" as const,
        sales: 456,
        rating: 4.8,
        reviews: 78,
        description:
          "One-on-one personal training sessions with certified trainers.",
        isFavorite: false,
      },
      {
        id: "13",
        name: "Nutrition Consultation",
        price: 99,
        image: "/placeholder.svg?height=200&width=280",
        business: "HealthPlus Wellness",
        category: "Health",
        type: "service" as const,
        sales: 234,
        rating: 4.7,
        reviews: 56,
        description: "Personalized nutrition plans and dietary consultations.",
        isFavorite: false,
      },
      {
        id: "14",
        name: "Yoga Classes",
        price: 79,
        image: "/placeholder.svg?height=200&width=280",
        business: "HealthPlus Wellness",
        category: "Health",
        type: "service" as const,
        sales: 789,
        rating: 4.6,
        reviews: 167,
        description: "Group and private yoga classes for all skill levels.",
        isFavorite: true,
      },
      {
        id: "15",
        name: "Massage Therapy",
        price: 129,
        image: "/placeholder.svg?height=200&width=280",
        business: "HealthPlus Wellness",
        category: "Health",
        type: "service" as const,
        sales: 345,
        rating: 4.9,
        reviews: 89,
        description:
          "Therapeutic massage sessions for relaxation and pain relief.",
        isFavorite: false,
      },
      {
        id: "16",
        name: "Mental Health Counseling",
        price: 149,
        image: "/placeholder.svg?height=200&width=280",
        business: "HealthPlus Wellness",
        category: "Health",
        type: "service" as const,
        sales: 123,
        rating: 4.8,
        reviews: 45,
        description:
          "Professional mental health counseling and therapy sessions.",
        isFavorite: false,
      },
    ],
  },
  {
    id: "4",
    name: "EduMaster Academy",
    logo: "/placeholder.svg",
    description: "Online education and skill development",
    trending: [
      {
        id: "401",
        name: "Programming Textbook Set",
        price: 149,
        image: "/placeholder.svg?height=200&width=280",
        business: "EduMaster Academy",
        category: "Books",
        type: "goods" as const,
        sales: 567,
        rating: 4.8,
        reviews: 123,
        description:
          "Complete set of 5 programming textbooks covering Python, JavaScript, and more.",
        isFavorite: false,
      },
      {
        id: "402",
        name: "Online Course Bundle",
        price: 399,
        image: "/placeholder.svg?height=200&width=280",
        business: "EduMaster Academy",
        category: "Education",
        type: "goods" as const,
        sales: 890,
        rating: 4.9,
        reviews: 234,
        description:
          "Lifetime access to 20+ online courses in technology and business.",
        isFavorite: true,
      },
      {
        id: "17",
        name: "Web Development Course",
        price: 199,
        image: "/placeholder.svg?height=200&width=280",
        business: "EduMaster Academy",
        category: "Education",
        type: "service" as const,
        sales: 1234,
        rating: 4.8,
        reviews: 298,
        description:
          "Complete web development course from beginner to advanced level.",
        isFavorite: false,
      },
    ],
    bestSellers: [
      {
        id: "403",
        name: "Study Planner Journal",
        price: 29,
        image: "/placeholder.svg?height=200&width=280",
        business: "EduMaster Academy",
        category: "Stationery",
        type: "goods" as const,
        sales: 1456,
        rating: 4.7,
        reviews: 345,
        description:
          "Comprehensive study planner with goal tracking and progress monitoring.",
        isFavorite: false,
      },
      {
        id: "404",
        name: "Laptop Stand Ergonomic",
        price: 79,
        image: "/placeholder.svg?height=200&width=280",
        business: "EduMaster Academy",
        category: "Office",
        type: "goods" as const,
        sales: 987,
        rating: 4.6,
        reviews: 234,
        description:
          "Adjustable laptop stand for better posture during study sessions.",
        isFavorite: false,
      },
      {
        id: "18",
        name: "Data Science Bootcamp",
        price: 299,
        image: "/placeholder.svg?height=200&width=280",
        business: "EduMaster Academy",
        category: "Education",
        type: "service" as const,
        sales: 567,
        rating: 4.9,
        reviews: 156,
        description: "Intensive data science bootcamp with hands-on projects.",
        isFavorite: true,
      },
      {
        id: "19",
        name: "Language Learning",
        price: 89,
        image: "/placeholder.svg?height=200&width=280",
        business: "EduMaster Academy",
        category: "Education",
        type: "service" as const,
        sales: 890,
        rating: 4.6,
        reviews: 234,
        description:
          "Interactive language learning courses in multiple languages.",
        isFavorite: false,
      },
    ],
    goods: [
      {
        id: "405",
        name: "Noise Cancelling Headphones",
        price: 199,
        image: "/placeholder.svg?height=200&width=280",
        business: "EduMaster Academy",
        category: "Electronics",
        type: "goods" as const,
        sales: 456,
        rating: 4.8,
        reviews: 98,
        description:
          "Premium noise-cancelling headphones perfect for focused studying.",
        isFavorite: true,
      },
      {
        id: "406",
        name: "Digital Note Tablet",
        price: 249,
        image: "/placeholder.svg?height=200&width=280",
        business: "EduMaster Academy",
        category: "Electronics",
        type: "goods" as const,
        sales: 345,
        rating: 4.7,
        reviews: 78,
        description:
          "Digital note-taking tablet with stylus and cloud synchronization.",
        isFavorite: false,
      },
      {
        id: "407",
        name: "Reference Book Collection",
        price: 199,
        image: "/placeholder.svg?height=200&width=280",
        business: "EduMaster Academy",
        category: "Books",
        type: "goods" as const,
        sales: 234,
        rating: 4.6,
        reviews: 67,
        description:
          "Collection of essential reference books for various academic subjects.",
        isFavorite: false,
      },
      {
        id: "408",
        name: "Calculator Scientific",
        price: 89,
        image: "/placeholder.svg?height=200&width=280",
        business: "EduMaster Academy",
        category: "Electronics",
        type: "goods" as const,
        sales: 567,
        rating: 4.5,
        reviews: 123,
        description:
          "Advanced scientific calculator with graphing capabilities.",
        isFavorite: false,
      },
      {
        id: "409",
        name: "Desk Organizer Set",
        price: 49,
        image: "/placeholder.svg?height=200&width=280",
        business: "EduMaster Academy",
        category: "Office",
        type: "goods" as const,
        sales: 789,
        rating: 4.4,
        reviews: 167,
        description:
          "Complete desk organizer set with compartments for all study supplies.",
        isFavorite: false,
      },
      {
        id: "410",
        name: "Blue Light Glasses",
        price: 39,
        image: "/placeholder.svg?height=200&width=280",
        business: "EduMaster Academy",
        category: "Health & Wellness",
        type: "goods" as const,
        sales: 678,
        rating: 4.3,
        reviews: 145,
        description:
          "Blue light blocking glasses to reduce eye strain during screen time.",
        isFavorite: false,
      },
    ],
    services: [
      {
        id: "17",
        name: "Web Development Course",
        price: 199,
        image: "/placeholder.svg?height=200&width=280",
        business: "EduMaster Academy",
        category: "Education",
        type: "service" as const,
        sales: 1234,
        rating: 4.8,
        reviews: 298,
        description:
          "Complete web development course from beginner to advanced level.",
        isFavorite: false,
      },
      {
        id: "18",
        name: "Data Science Bootcamp",
        price: 299,
        image: "/placeholder.svg?height=200&width=280",
        business: "EduMaster Academy",
        category: "Education",
        type: "service" as const,
        sales: 567,
        rating: 4.9,
        reviews: 156,
        description: "Intensive data science bootcamp with hands-on projects.",
        isFavorite: true,
      },
      {
        id: "19",
        name: "Language Learning",
        price: 89,
        image: "/placeholder.svg?height=200&width=280",
        business: "EduMaster Academy",
        category: "Education",
        type: "service" as const,
        sales: 890,
        rating: 4.6,
        reviews: 234,
        description:
          "Interactive language learning courses in multiple languages.",
        isFavorite: false,
      },
      {
        id: "20",
        name: "Business Analytics",
        price: 249,
        image: "/placeholder.svg?height=200&width=280",
        business: "EduMaster Academy",
        category: "Education",
        type: "service" as const,
        sales: 345,
        rating: 4.7,
        reviews: 98,
        description:
          "Business analytics and data visualization certification course.",
        isFavorite: false,
      },
      {
        id: "21",
        name: "Digital Marketing Mastery",
        price: 179,
        image: "/placeholder.svg?height=200&width=280",
        business: "EduMaster Academy",
        category: "Education",
        type: "service" as const,
        sales: 678,
        rating: 4.5,
        reviews: 145,
        description:
          "Comprehensive digital marketing course with practical case studies.",
        isFavorite: false,
      },
    ],
  },
  {
    id: "5",
    name: "LegalPro Services",
    logo: "/placeholder.svg",
    description: "Professional legal consultation and services",
    trending: [
      {
        id: "501",
        name: "Legal Document Templates",
        price: 99,
        image: "/placeholder.svg?height=200&width=280",
        business: "LegalPro Services",
        category: "Legal",
        type: "goods" as const,
        sales: 345,
        rating: 4.7,
        reviews: 78,
        description:
          "Comprehensive collection of legal document templates for businesses.",
        isFavorite: false,
      },
      {
        id: "502",
        name: "Business Law Handbook",
        price: 79,
        image: "/placeholder.svg?height=200&width=280",
        business: "LegalPro Services",
        category: "Books",
        type: "goods" as const,
        sales: 567,
        rating: 4.8,
        reviews: 123,
        description:
          "Essential business law handbook with case studies and practical examples.",
        isFavorite: true,
      },
      {
        id: "24",
        name: "Intellectual Property",
        price: 299,
        image: "/placeholder.svg?height=200&width=280",
        business: "LegalPro Services",
        category: "Legal",
        type: "service" as const,
        sales: 123,
        rating: 4.9,
        reviews: 34,
        description:
          "Intellectual property protection and trademark registration.",
        isFavorite: true,
      },
    ],
    bestSellers: [
      {
        id: "503",
        name: "Contract Management Software",
        price: 199,
        image: "/placeholder.svg?height=200&width=280",
        business: "LegalPro Services",
        category: "Software",
        type: "goods" as const,
        sales: 987,
        rating: 4.6,
        reviews: 234,
        description:
          "Digital contract management software with e-signature capabilities.",
        isFavorite: false,
      },
      {
        id: "504",
        name: "Legal Forms Bundle",
        price: 149,
        image: "/placeholder.svg?height=200&width=280",
        business: "LegalPro Services",
        category: "Legal",
        type: "goods" as const,
        sales: 678,
        rating: 4.5,
        reviews: 145,
        description:
          "Complete bundle of 100+ legal forms for various business needs.",
        isFavorite: false,
      },
      {
        id: "22",
        name: "Business Law Consultation",
        price: 199,
        image: "/placeholder.svg?height=200&width=280",
        business: "LegalPro Services",
        category: "Legal",
        type: "service" as const,
        sales: 234,
        rating: 4.8,
        reviews: 67,
        description:
          "Expert business law consultation for startups and enterprises.",
        isFavorite: false,
      },
      {
        id: "23",
        name: "Contract Review",
        price: 149,
        image: "/placeholder.svg?height=200&width=280",
        business: "LegalPro Services",
        category: "Legal",
        type: "service" as const,
        sales: 456,
        rating: 4.7,
        reviews: 89,
        description:
          "Professional contract review and legal document analysis.",
        isFavorite: false,
      },
    ],
    goods: [
      {
        id: "505",
        name: "Legal Research Database Access",
        price: 299,
        image: "/placeholder.svg?height=200&width=280",
        business: "LegalPro Services",
        category: "Software",
        type: "goods" as const,
        sales: 234,
        rating: 4.8,
        reviews: 67,
        description:
          "One-year access to comprehensive legal research database.",
        isFavorite: false,
      },
      {
        id: "506",
        name: "Compliance Checklist Guide",
        price: 59,
        image: "/placeholder.svg?height=200&width=280",
        business: "LegalPro Services",
        category: "Legal",
        type: "goods" as const,
        sales: 456,
        rating: 4.6,
        reviews: 98,
        description:
          "Comprehensive compliance checklist for different business types.",
        isFavorite: false,
      },
      {
        id: "507",
        name: "Privacy Policy Generator",
        price: 89,
        image: "/placeholder.svg?height=200&width=280",
        business: "LegalPro Services",
        category: "Software",
        type: "goods" as const,
        sales: 345,
        rating: 4.7,
        reviews: 78,
        description:
          "Automated privacy policy and terms of service generator tool.",
        isFavorite: true,
      },
      {
        id: "508",
        name: "Legal Terminology Dictionary",
        price: 39,
        image: "/placeholder.svg?height=200&width=280",
        business: "LegalPro Services",
        category: "Books",
        type: "goods" as const,
        sales: 567,
        rating: 4.4,
        reviews: 123,
        description: "Comprehensive dictionary of legal terms and definitions.",
        isFavorite: false,
      },
      {
        id: "509",
        name: "Document Scanner Professional",
        price: 199,
        image: "/placeholder.svg?height=200&width=280",
        business: "LegalPro Services",
        category: "Electronics",
        type: "goods" as const,
        sales: 234,
        rating: 4.5,
        reviews: 67,
        description:
          "High-speed document scanner for legal document digitization.",
        isFavorite: false,
      },
      {
        id: "510",
        name: "Legal Case Management App",
        price: 129,
        image: "/placeholder.svg?height=200&width=280",
        business: "LegalPro Services",
        category: "Software",
        type: "goods" as const,
        sales: 345,
        rating: 4.6,
        reviews: 78,
        description:
          "Mobile app for legal case management and client communication.",
        isFavorite: false,
      },
    ],
    services: [
      {
        id: "22",
        name: "Business Law Consultation",
        price: 199,
        image: "/placeholder.svg?height=200&width=280",
        business: "LegalPro Services",
        category: "Legal",
        type: "service" as const,
        sales: 234,
        rating: 4.8,
        reviews: 67,
        description:
          "Expert business law consultation for startups and enterprises.",
        isFavorite: false,
      },
      {
        id: "23",
        name: "Contract Review",
        price: 149,
        image: "/placeholder.svg?height=200&width=280",
        business: "LegalPro Services",
        category: "Legal",
        type: "service" as const,
        sales: 456,
        rating: 4.7,
        reviews: 89,
        description:
          "Professional contract review and legal document analysis.",
        isFavorite: false,
      },
      {
        id: "24",
        name: "Intellectual Property",
        price: 299,
        image: "/placeholder.svg?height=200&width=280",
        business: "LegalPro Services",
        category: "Legal",
        type: "service" as const,
        sales: 123,
        rating: 4.9,
        reviews: 34,
        description:
          "Intellectual property protection and trademark registration.",
        isFavorite: true,
      },
      {
        id: "25",
        name: "Employment Law",
        price: 179,
        image: "/placeholder.svg?height=200&width=280",
        business: "LegalPro Services",
        category: "Legal",
        type: "service" as const,
        sales: 345,
        rating: 4.6,
        reviews: 78,
        description: "Employment law consultation and workplace compliance.",
        isFavorite: false,
      },
    ],
  },
  {
    id: "6",
    name: "HomeStyle Interiors",
    logo: "/placeholder.svg",
    description: "Interior design and home improvement services",
    trending: [
      {
        id: "601",
        name: "Smart LED Light Strips",
        price: 89,
        image: "/placeholder.svg?height=200&width=280",
        business: "HomeStyle Interiors",
        category: "Home & Garden",
        type: "goods" as const,
        sales: 789,
        rating: 4.6,
        reviews: 167,
        description:
          "WiFi-controlled LED light strips with color changing and app control.",
        isFavorite: false,
      },
      {
        id: "602",
        name: "Decorative Wall Art Set",
        price: 129,
        image: "/placeholder.svg?height=200&width=280",
        business: "HomeStyle Interiors",
        category: "Home & Garden",
        type: "goods" as const,
        sales: 567,
        rating: 4.8,
        reviews: 123,
        description:
          "Modern abstract wall art set of 3 pieces for contemporary homes.",
        isFavorite: true,
      },
      {
        id: "29",
        name: "Kitchen Design",
        price: 399,
        image: "/placeholder.svg?height=200&width=280",
        business: "HomeStyle Interiors",
        category: "Design",
        type: "service" as const,
        sales: 156,
        rating: 4.9,
        reviews: 45,
        description: "Complete kitchen design and renovation planning service.",
        isFavorite: true,
      },
    ],
    bestSellers: [
      {
        id: "603",
        name: "Throw Pillow Collection",
        price: 79,
        image: "/placeholder.svg?height=200&width=280",
        business: "HomeStyle Interiors",
        category: "Home & Garden",
        type: "goods" as const,
        sales: 1234,
        rating: 4.7,
        reviews: 267,
        description:
          "Set of 4 luxury throw pillows in coordinating colors and textures.",
        isFavorite: false,
      },
      {
        id: "604",
        name: "Area Rug Modern",
        price: 199,
        image: "/placeholder.svg?height=200&width=280",
        business: "HomeStyle Interiors",
        category: "Home & Garden",
        type: "goods" as const,
        sales: 890,
        rating: 4.6,
        reviews: 234,
        description:
          "Modern geometric area rug available in multiple sizes and colors.",
        isFavorite: false,
      },
      {
        id: "26",
        name: "Interior Design Consultation",
        price: 199,
        image: "/placeholder.svg?height=200&width=280",
        business: "HomeStyle Interiors",
        category: "Design",
        type: "service" as const,
        sales: 567,
        rating: 4.8,
        reviews: 123,
        description:
          "Professional interior design consultation and space planning.",
        isFavorite: false,
      },
      {
        id: "27",
        name: "Home Staging",
        price: 299,
        image: "/placeholder.svg?height=200&width=280",
        business: "HomeStyle Interiors",
        category: "Design",
        type: "service" as const,
        sales: 234,
        rating: 4.7,
        reviews: 67,
        description:
          "Professional home staging for real estate sales and rentals.",
        isFavorite: false,
      },
    ],
    goods: [
      {
        id: "605",
        name: "Curtain Set Blackout",
        price: 99,
        image: "/placeholder.svg?height=200&width=280",
        business: "HomeStyle Interiors",
        category: "Home & Garden",
        type: "goods" as const,
        sales: 456,
        rating: 4.5,
        reviews: 98,
        description:
          "Energy-efficient blackout curtains with thermal insulation properties.",
        isFavorite: false,
      },
      {
        id: "606",
        name: "Table Lamp Modern",
        price: 149,
        image: "/placeholder.svg?height=200&width=280",
        business: "HomeStyle Interiors",
        category: "Home & Garden",
        type: "goods" as const,
        sales: 345,
        rating: 4.7,
        reviews: 78,
        description:
          "Contemporary table lamp with adjustable brightness and USB charging.",
        isFavorite: false,
      },
      {
        id: "607",
        name: "Storage Ottoman",
        price: 89,
        image: "/placeholder.svg?height=200&width=280",
        business: "HomeStyle Interiors",
        category: "Furniture",
        type: "goods" as const,
        sales: 567,
        rating: 4.6,
        reviews: 123,
        description:
          "Multi-functional storage ottoman that doubles as seating and storage.",
        isFavorite: true,
      },
      {
        id: "608",
        name: "Wall Mirror Decorative",
        price: 119,
        image: "/placeholder.svg?height=200&width=280",
        business: "HomeStyle Interiors",
        category: "Home & Garden",
        type: "goods" as const,
        sales: 234,
        rating: 4.8,
        reviews: 67,
        description: "Large decorative wall mirror with elegant frame design.",
        isFavorite: false,
      },
      {
        id: "609",
        name: "Plant Pot Set Ceramic",
        price: 59,
        image: "/placeholder.svg?height=200&width=280",
        business: "HomeStyle Interiors",
        category: "Home & Garden",
        type: "goods" as const,
        sales: 789,
        rating: 4.4,
        reviews: 167,
        description:
          "Set of 3 ceramic plant pots with drainage holes and saucers.",
        isFavorite: false,
      },
      {
        id: "610",
        name: "Accent Chair Velvet",
        price: 299,
        image: "/placeholder.svg?height=200&width=280",
        business: "HomeStyle Interiors",
        category: "Furniture",
        type: "goods" as const,
        sales: 156,
        rating: 4.9,
        reviews: 45,
        description:
          "Luxury velvet accent chair with gold metal legs for living room.",
        isFavorite: false,
      },
    ],
    services: [
      {
        id: "26",
        name: "Interior Design Consultation",
        price: 199,
        image: "/placeholder.svg?height=200&width=280",
        business: "HomeStyle Interiors",
        category: "Design",
        type: "service" as const,
        sales: 567,
        rating: 4.8,
        reviews: 123,
        description:
          "Professional interior design consultation and space planning.",
        isFavorite: false,
      },
      {
        id: "27",
        name: "Home Staging",
        price: 299,
        image: "/placeholder.svg?height=200&width=280",
        business: "HomeStyle Interiors",
        category: "Design",
        type: "service" as const,
        sales: 234,
        rating: 4.7,
        reviews: 67,
        description:
          "Professional home staging for real estate sales and rentals.",
        isFavorite: false,
      },
      {
        id: "28",
        name: "Color Consultation",
        price: 99,
        image: "/placeholder.svg?height=200&width=280",
        business: "HomeStyle Interiors",
        category: "Design",
        type: "service" as const,
        sales: 789,
        rating: 4.6,
        reviews: 156,
        description:
          "Expert color consultation and paint selection for your space.",
        isFavorite: false,
      },
      {
        id: "29",
        name: "Kitchen Design",
        price: 399,
        image: "/placeholder.svg?height=200&width=280",
        business: "HomeStyle Interiors",
        category: "Design",
        type: "service" as const,
        sales: 156,
        rating: 4.9,
        reviews: 45,
        description: "Complete kitchen design and renovation planning service.",
        isFavorite: true,
      },
      {
        id: "30",
        name: "Bathroom Renovation",
        price: 349,
        image: "/placeholder.svg?height=200&width=280",
        business: "HomeStyle Interiors",
        category: "Design",
        type: "service" as const,
        sales: 123,
        rating: 4.7,
        reviews: 34,
        description: "Bathroom renovation design and project management.",
        isFavorite: false,
      },
    ],
  },
  {
    id: "7",
    name: "AutoCare Express",
    logo: "/placeholder.svg",
    description: "Comprehensive automotive services and maintenance",
    trending: [
      {
        id: "701",
        name: "Car Phone Mount Magnetic",
        price: 29,
        image: "/placeholder.svg?height=200&width=280",
        business: "AutoCare Express",
        category: "Automotive",
        type: "goods" as const,
        sales: 1234,
        rating: 4.5,
        reviews: 267,
        description:
          "Strong magnetic phone mount for dashboard with 360-degree rotation.",
        isFavorite: false,
      },
      {
        id: "702",
        name: "Car Dash Cam HD",
        price: 149,
        image: "/placeholder.svg?height=200&width=280",
        business: "AutoCare Express",
        category: "Automotive",
        type: "goods" as const,
        sales: 567,
        rating: 4.7,
        reviews: 123,
        description:
          "1080p HD dash cam with night vision and automatic recording.",
        isFavorite: true,
      },
      {
        id: "33",
        name: "Car Detailing",
        price: 129,
        image: "/placeholder.svg?height=200&width=280",
        business: "AutoCare Express",
        category: "Automotive",
        type: "service" as const,
        sales: 456,
        rating: 4.8,
        reviews: 156,
        description:
          "Complete car detailing service including interior and exterior cleaning.",
        isFavorite: true,
      },
    ],
    bestSellers: [
      {
        id: "703",
        name: "Car Emergency Kit",
        price: 89,
        image: "/placeholder.svg?height=200&width=280",
        business: "AutoCare Express",
        category: "Automotive",
        type: "goods" as const,
        sales: 890,
        rating: 4.8,
        reviews: 234,
        description:
          "Complete emergency kit with jumper cables, tools, and safety equipment.",
        isFavorite: false,
      },
      {
        id: "704",
        name: "Motor Oil Premium Synthetic",
        price: 39,
        image: "/placeholder.svg?height=200&width=280",
        business: "AutoCare Express",
        category: "Automotive",
        type: "goods" as const,
        sales: 2345,
        rating: 4.6,
        reviews: 456,
        description:
          "High-performance synthetic motor oil for enhanced engine protection.",
        isFavorite: false,
      },
      {
        id: "31",
        name: "Oil Change Service",
        price: 49,
        image: "/placeholder.svg?height=200&width=280",
        business: "AutoCare Express",
        category: "Automotive",
        type: "service" as const,
        sales: 1234,
        rating: 4.5,
        reviews: 234,
        description:
          "Quick and professional oil change service with quality oil.",
        isFavorite: false,
      },
      {
        id: "34",
        name: "Tire Replacement",
        price: 199,
        image: "/placeholder.svg?height=200&width=280",
        business: "AutoCare Express",
        category: "Automotive",
        type: "service" as const,
        sales: 345,
        rating: 4.6,
        reviews: 78,
        description:
          "Professional tire installation and wheel alignment service.",
        isFavorite: false,
      },
    ],
    goods: [
      {
        id: "705",
        name: "Car Air Freshener Set",
        price: 19,
        image: "/placeholder.svg?height=200&width=280",
        business: "AutoCare Express",
        category: "Automotive",
        type: "goods" as const,
        sales: 1567,
        rating: 4.3,
        reviews: 345,
        description:
          "Set of 6 long-lasting car air fresheners in various scents.",
        isFavorite: false,
      },
      {
        id: "706",
        name: "Tire Pressure Gauge Digital",
        price: 25,
        image: "/placeholder.svg?height=200&width=280",
        business: "AutoCare Express",
        category: "Automotive",
        type: "goods" as const,
        sales: 789,
        rating: 4.5,
        reviews: 167,
        description:
          "Accurate digital tire pressure gauge with LED display and auto-shutoff.",
        isFavorite: false,
      },
      {
        id: "707",
        name: "Car Seat Covers Universal",
        price: 79,
        image: "/placeholder.svg?height=200&width=280",
        business: "AutoCare Express",
        category: "Automotive",
        type: "goods" as const,
        sales: 456,
        rating: 4.4,
        reviews: 98,
        description:
          "Water-resistant universal car seat covers for front and rear seats.",
        isFavorite: false,
      },
      {
        id: "708",
        name: "Car Vacuum Cordless",
        price: 99,
        image: "/placeholder.svg?height=200&width=280",
        business: "AutoCare Express",
        category: "Automotive",
        type: "goods" as const,
        sales: 345,
        rating: 4.6,
        reviews: 78,
        description:
          "Powerful cordless car vacuum with multiple attachments and long battery.",
        isFavorite: true,
      },
      {
        id: "709",
        name: "Windshield Washer Fluid",
        price: 12,
        image: "/placeholder.svg?height=200&width=280",
        business: "AutoCare Express",
        category: "Automotive",
        type: "goods" as const,
        sales: 2234,
        rating: 4.2,
        reviews: 456,
        description:
          "All-season windshield washer fluid with anti-freeze protection.",
        isFavorite: false,
      },
      {
        id: "710",
        name: "Jumper Cables Heavy Duty",
        price: 49,
        image: "/placeholder.svg?height=200&width=280",
        business: "AutoCare Express",
        category: "Automotive",
        type: "goods" as const,
        sales: 567,
        rating: 4.7,
        reviews: 123,
        description:
          "Heavy-duty jumper cables with tangle-free design and storage case.",
        isFavorite: false,
      },
    ],
    services: [
      {
        id: "31",
        name: "Oil Change Service",
        price: 49,
        image: "/placeholder.svg?height=200&width=280",
        business: "AutoCare Express",
        category: "Automotive",
        type: "service" as const,
        sales: 1234,
        rating: 4.5,
        reviews: 234,
        description:
          "Quick and professional oil change service with quality oil.",
        isFavorite: false,
      },
      {
        id: "32",
        name: "Brake Inspection",
        price: 79,
        image: "/placeholder.svg?height=200&width=280",
        business: "AutoCare Express",
        category: "Automotive",
        type: "service" as const,
        sales: 567,
        rating: 4.7,
        reviews: 89,
        description: "Comprehensive brake system inspection and safety check.",
        isFavorite: false,
      },
      {
        id: "33",
        name: "Car Detailing",
        price: 129,
        image: "/placeholder.svg?height=200&width=280",
        business: "AutoCare Express",
        category: "Automotive",
        type: "service" as const,
        sales: 456,
        rating: 4.8,
        reviews: 156,
        description:
          "Complete car detailing service including interior and exterior cleaning.",
        isFavorite: true,
      },
      {
        id: "34",
        name: "Tire Replacement",
        price: 199,
        image: "/placeholder.svg?height=200&width=280",
        business: "AutoCare Express",
        category: "Automotive",
        type: "service" as const,
        sales: 345,
        rating: 4.6,
        reviews: 78,
        description:
          "Professional tire installation and wheel alignment service.",
        isFavorite: false,
      },
      {
        id: "35",
        name: "Engine Diagnostics",
        price: 99,
        image: "/placeholder.svg?height=200&width=280",
        business: "AutoCare Express",
        category: "Automotive",
        type: "service" as const,
        sales: 234,
        rating: 4.7,
        reviews: 67,
        description: "Advanced engine diagnostics and performance analysis.",
        isFavorite: false,
      },
    ],
  },
  {
    id: "8",
    name: "PetCare Plus",
    logo: "/placeholder.svg",
    description: "Complete pet care and veterinary services",
    trending: [
      {
        id: "801",
        name: "Dog Toy Interactive Puzzle",
        price: 39,
        image: "/placeholder.svg?height=200&width=280",
        business: "PetCare Plus",
        category: "Pet Care",
        type: "goods" as const,
        sales: 678,
        rating: 4.7,
        reviews: 145,
        description:
          "Mental stimulation puzzle toy to keep dogs engaged and entertained.",
        isFavorite: false,
      },
      {
        id: "802",
        name: "Cat Litter Premium Clumping",
        price: 29,
        image: "/placeholder.svg?height=200&width=280",
        business: "PetCare Plus",
        category: "Pet Care",
        type: "goods" as const,
        sales: 1234,
        rating: 4.5,
        reviews: 267,
        description:
          "Odor-control clumping cat litter made from natural materials.",
        isFavorite: true,
      },
      {
        id: "38",
        name: "Pet Training",
        price: 149,
        image: "/placeholder.svg?height=200&width=280",
        business: "PetCare Plus",
        category: "Pet Care",
        type: "service" as const,
        sales: 234,
        rating: 4.7,
        reviews: 67,
        description:
          "Professional pet training and behavior modification sessions.",
        isFavorite: true,
      },
    ],
    bestSellers: [
      {
        id: "803",
        name: "Pet Food Bowl Set",
        price: 49,
        image: "/placeholder.svg?height=200&width=280",
        business: "PetCare Plus",
        category: "Pet Care",
        type: "goods" as const,
        sales: 1567,
        rating: 4.6,
        reviews: 345,
        description:
          "Non-slip stainless steel food and water bowl set for pets.",
        isFavorite: false,
      },
      {
        id: "804",
        name: "Dog Leash Retractable",
        price: 35,
        image: "/placeholder.svg?height=200&width=280",
        business: "PetCare Plus",
        category: "Pet Care",
        type: "goods" as const,
        sales: 890,
        rating: 4.4,
        reviews: 234,
        description:
          "Durable retractable dog leash with comfortable grip and safety lock.",
        isFavorite: false,
      },
      {
        id: "36",
        name: "Pet Grooming",
        price: 79,
        image: "/placeholder.svg?height=200&width=280",
        business: "PetCare Plus",
        category: "Pet Care",
        type: "service" as const,
        sales: 678,
        rating: 4.8,
        reviews: 145,
        description: "Professional pet grooming service for dogs and cats.",
        isFavorite: false,
      },
      {
        id: "37",
        name: "Veterinary Checkup",
        price: 99,
        image: "/placeholder.svg?height=200&width=280",
        business: "PetCare Plus",
        category: "Pet Care",
        type: "service" as const,
        sales: 456,
        rating: 4.9,
        reviews: 123,
        description:
          "Comprehensive veterinary health checkup and wellness exam.",
        isFavorite: false,
      },
    ],
    goods: [
      {
        id: "805",
        name: "Pet Carrier Travel",
        price: 89,
        image: "/placeholder.svg?height=200&width=280",
        business: "PetCare Plus",
        category: "Pet Care",
        type: "goods" as const,
        sales: 345,
        rating: 4.7,
        reviews: 78,
        description:
          "Airline-approved pet carrier with comfortable padding and ventilation.",
        isFavorite: false,
      },
      {
        id: "806",
        name: "Cat Scratching Post",
        price: 59,
        image: "/placeholder.svg?height=200&width=280",
        business: "PetCare Plus",
        category: "Pet Care",
        type: "goods" as const,
        sales: 567,
        rating: 4.6,
        reviews: 123,
        description:
          "Tall sisal scratching post with multiple levels and hanging toys.",
        isFavorite: false,
      },
      {
        id: "807",
        name: "Dog Bed Memory Foam",
        price: 119,
        image: "/placeholder.svg?height=200&width=280",
        business: "PetCare Plus",
        category: "Pet Care",
        type: "goods" as const,
        sales: 234,
        rating: 4.8,
        reviews: 67,
        description:
          "Orthopedic memory foam dog bed with removable washable cover.",
        isFavorite: true,
      },
      {
        id: "808",
        name: "Pet Shampoo Organic",
        price: 25,
        image: "/placeholder.svg?height=200&width=280",
        business: "PetCare Plus",
        category: "Pet Care",
        type: "goods" as const,
        sales: 789,
        rating: 4.5,
        reviews: 167,
        description:
          "Gentle organic pet shampoo with natural ingredients and pleasant scent.",
        isFavorite: false,
      },
      {
        id: "809",
        name: "Pet Water Fountain",
        price: 79,
        image: "/placeholder.svg?height=200&width=280",
        business: "PetCare Plus",
        category: "Pet Care",
        type: "goods" as const,
        sales: 456,
        rating: 4.7,
        reviews: 98,
        description:
          "Automatic pet water fountain with filter system and quiet operation.",
        isFavorite: false,
      },
      {
        id: "810",
        name: "Pet Treat Variety Pack",
        price: 39,
        image: "/placeholder.svg?height=200&width=280",
        business: "PetCare Plus",
        category: "Pet Care",
        type: "goods" as const,
        sales: 1123,
        rating: 4.4,
        reviews: 245,
        description:
          "Assorted healthy pet treats made with natural ingredients and flavors.",
        isFavorite: false,
      },
    ],
    services: [
      {
        id: "36",
        name: "Pet Grooming",
        price: 79,
        image: "/placeholder.svg?height=200&width=280",
        business: "PetCare Plus",
        category: "Pet Care",
        type: "service" as const,
        sales: 678,
        rating: 4.8,
        reviews: 145,
        description: "Professional pet grooming service for dogs and cats.",
        isFavorite: false,
      },
      {
        id: "37",
        name: "Veterinary Checkup",
        price: 99,
        image: "/placeholder.svg?height=200&width=280",
        business: "PetCare Plus",
        category: "Pet Care",
        type: "service" as const,
        sales: 456,
        rating: 4.9,
        reviews: 123,
        description:
          "Comprehensive veterinary health checkup and wellness exam.",
        isFavorite: false,
      },
      {
        id: "38",
        name: "Pet Training",
        price: 149,
        image: "/placeholder.svg?height=200&width=280",
        business: "PetCare Plus",
        category: "Pet Care",
        type: "service" as const,
        sales: 234,
        rating: 4.7,
        reviews: 67,
        description:
          "Professional pet training and behavior modification sessions.",
        isFavorite: true,
      },
      {
        id: "39",
        name: "Pet Boarding",
        price: 59,
        image: "/placeholder.svg?height=200&width=280",
        business: "PetCare Plus",
        category: "Pet Care",
        type: "service" as const,
        sales: 567,
        rating: 4.6,
        reviews: 89,
        description:
          "Safe and comfortable pet boarding services with playtime.",
        isFavorite: false,
      },
      {
        id: "40",
        name: "Emergency Care",
        price: 199,
        image: "/placeholder.svg?height=200&width=280",
        business: "PetCare Plus",
        category: "Pet Care",
        type: "service" as const,
        sales: 123,
        rating: 4.8,
        reviews: 34,
        description:
          "24/7 emergency veterinary care and urgent medical treatment.",
        isFavorite: false,
      },
    ],
  },
];

// Favorites management with localStorage persistence
const FAVORITES_STORAGE_KEY = "fusumi-favorites";

// Get favorites from localStorage
const getFavoritesFromStorage = (): Set<string> => {
  if (typeof window === "undefined") return new Set(); // SSR safety

  try {
    const stored = localStorage.getItem(FAVORITES_STORAGE_KEY);
    return stored ? new Set(JSON.parse(stored)) : new Set();
  } catch {
    return new Set();
  }
};

// Save favorites to localStorage
const saveFavoritesToStorage = (favorites: Set<string>) => {
  if (typeof window === "undefined") return; // SSR safety

  try {
    localStorage.setItem(
      FAVORITES_STORAGE_KEY,
      JSON.stringify(Array.from(favorites))
    );
  } catch (error) {
    console.warn("Failed to save favorites to localStorage:", error);
  }
};

// Global favorites state
let globalFavorites = getFavoritesFromStorage();

// Function to toggle favorite status with localStorage persistence
export const toggleFavorite = (productId: string): boolean => {
  if (globalFavorites.has(productId)) {
    globalFavorites.delete(productId);
  } else {
    globalFavorites.add(productId);
  }

  // Save to localStorage
  saveFavoritesToStorage(globalFavorites);

  const isFavorite = globalFavorites.has(productId);
  return isFavorite;
};

// Function to get favorite status of a product
export const getFavoriteStatus = (productId: string): boolean => {
  return globalFavorites.has(productId);
};

// Function to get all current favorites
export const getAllFavorites = (): string[] => {
  return Array.from(globalFavorites);
};

// Function to clear all favorites
export const clearAllFavorites = (): void => {
  globalFavorites.clear();
  saveFavoritesToStorage(globalFavorites);
};

// Function to initialize favorites (call this when app starts)
export const initializeFavorites = (): void => {
  globalFavorites = getFavoritesFromStorage();
};

// Helper function to get products with favorite status applied
export const getProductsWithFavorites = (products: any[]): any[] => {
  return products.map((product) => ({
    ...product,
    isFavorite: getFavoriteStatus(product.id),
  }));
};

// Helper function to get business data with favorites applied
export const getBusinessWithFavorites = (businessId: string) => {
  const business = mockBusinesses.find((b) => b.id === businessId);
  if (!business) return null;

  return {
    ...business,
    trending: getProductsWithFavorites(business.trending),
    bestSellers: getProductsWithFavorites(business.bestSellers),
    goods: getProductsWithFavorites(business.goods),
    services: getProductsWithFavorites(business.services),
  };
};

// Helper function to get all businesses with favorites applied
export const getAllBusinessesWithFavorites = () => {
  return mockBusinesses.map((business) => ({
    ...business,
    trending: getProductsWithFavorites(business.trending),
    bestSellers: getProductsWithFavorites(business.bestSellers),
    goods: getProductsWithFavorites(business.goods),
    services: getProductsWithFavorites(business.services),
  }));
};
